apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
      - name: task
        image: task-service:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: task-env
